#!/usr/bin/env python3
"""new-profile.py -- scaffold a new vcctrl-<name>.yaml from a profile-kinds/
template. A REPO-AUTHORING-TIME tool, run by a person adding a new profile
to this rig; it never runs on the daemon host and vcctrld/vcconfig.py never
import it or read anything it reads.

CREATION-TIME ONLY, BY DESIGN. This writes a COMPLETE, self-contained
vcctrl-<name>.yaml -- the profile-kinds/<kind>.yaml template is read once,
here, and never again. vcctrld itself never merges a profile's config
against its kind at startup: a deployed profile's real settings must be
fully visible in its own file, the same way vcctrl-modernpc.example.yaml
already is, not partly inherited from a template that could change out from
under it later. See profile-kinds/vga-ps2.yaml's own comment for the fuller
reasoning.

Usage:
    tools/new-profile.py --kind hdmi-usb --name myserver
    tools/new-profile.py --list-kinds
"""
import argparse
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KINDS_DIR = os.path.join(REPO_ROOT, "profile-kinds")


def list_kinds():
    if not os.path.isdir(KINDS_DIR):
        return []
    return sorted(f[:-len(".yaml")] for f in os.listdir(KINDS_DIR)
                 if f.endswith(".yaml"))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--kind", help="one of: %s" % ", ".join(list_kinds()))
    ap.add_argument("--name",
                    help="profile name, e.g. 'myserver' -> vcctrl-myserver.yaml")
    ap.add_argument("--list-kinds", action="store_true",
                    help="print available kinds and exit")
    ap.add_argument("--out-dir", default=REPO_ROOT,
                    help="where to write vcctrl-<name>.yaml (default: repo root)")
    args = ap.parse_args()

    if args.list_kinds:
        for k in list_kinds():
            print(k)
        return 0

    if not args.kind or not args.name:
        ap.error("--kind and --name are required (or pass --list-kinds)")

    # NAME VALIDATION MATCHES discover_profiles()'s OWN NAMING CONVENTION
    # (daemon/vcctrld.py) and bin/vcctrl-client's profile_socket_path() --
    # both build /run/vcctrl-<name>.sock directly from this string with no
    # escaping. A name that is not a plain lowercase-ish token would
    # produce a socket path that looks fine here and is unreachable (or
    # worse, a path-traversal-shaped surprise) the moment vcctrld tries to
    # bind it.
    name = args.name.strip()
    if not name or not all(c.isalnum() or c in "-_" for c in name) \
            or name != name.lower():
        sys.stderr.write(
            "refusing name %r: must be lowercase letters/digits/-/_ only "
            "(it becomes /run/vcctrl-%s.sock literally, unescaped)\n"
            % (args.name, args.name))
        return 1
    if name == "default":
        sys.stderr.write(
            "refusing name 'default': that word is the FALLBACK LABEL "
            "bin/vcctrl-client's list_profiles() and Instance.label() use "
            "for an unnamed primary -- a real profile named 'default' "
            "would be indistinguishable from that fallback in every "
            "listing.\n")
        return 1

    kind_path = os.path.join(KINDS_DIR, "%s.yaml" % args.kind)
    if not os.path.isfile(kind_path):
        sys.stderr.write("no such kind %r -- available: %s\n"
                         % (args.kind, ", ".join(list_kinds())))
        return 1

    out_path = os.path.join(args.out_dir, "vcctrl-%s.yaml" % name)
    if os.path.exists(out_path):
        sys.stderr.write("refusing to overwrite existing %s\n" % out_path)
        return 1

    with open(kind_path, encoding="utf-8") as f:
        kind_body = f.read()

    # Strip the kind file's OWN header comment block (everything up to the
    # first blank line after the leading '#' block) -- that block explains
    # the KIND, not this specific profile, and would be confusing pasted
    # verbatim into a deployed config a person is meant to read on its own
    # terms. The kind's per-setting inline comments (REPLACE_ME markers,
    # capability-specific reasoning) are kept -- those ARE about this
    # profile once REPLACE_ME is filled in.
    lines = kind_body.splitlines()
    i = 0
    while i < len(lines) and (lines[i].startswith("#") or not lines[i].strip()):
        i += 1
    body = "\n".join(lines[i:]).lstrip("\n")

    header = (
        "# vcctrl configuration for profile %r -- generated by "
        "tools/new-profile.py from profile-kinds/%s.yaml.\n"
        "#\n"
        "# EVERY \"REPLACE_ME\" BELOW IS A REAL VALUE THIS FILE STILL NEEDS\n"
        "# before this profile can actually run -- device paths, plug\n"
        "# addresses, board names. This file is complete and self-\n"
        "# contained once they are filled in; nothing at runtime reads\n"
        "# profile-kinds/%s.yaml again (see that file's own comment).\n"
        "#\n"
        "# NOT gitignored by name the way vcctrl.yaml/vcctrl-modernpc.yaml\n"
        "# are (see .gitignore and vcctrl-repo-conventions) -- if this\n"
        "# profile's own settings turn out to hold anything host-real\n"
        "# (addresses, credentials), add it to .gitignore explicitly\n"
        "# before committing, the same way modernpc's config was.\n"
        "#\n"
        "# Deploy with: pi/deploy.sh --profile %s\n"
        "# (installs pi/files/vcctrld-<name>.service, a second vcctrld\n"
        "# process pointed at this file via VCCTRL_CONFIG -- see\n"
        "# pi/install.sh's install_profile().)\n\n"
        "version: 1\n\n"
        "daemon:\n"
        "  # THIS PROFILE'S OWN NAME (daemon/vcctrld.py's Instance.name).\n"
        "  # Only actually READ from the file that ends up loaded as the\n"
        "  # ROOT vcctrl.yaml (discover_profiles() derives a SIBLING's\n"
        "  # name from its filename instead, per that function's own\n"
        "  # comment) -- harmless, correct documentation either way.\n"
        "  profile_name: %s\n\n"
    ) % (name, args.kind, args.kind, name, name)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header + body)
        if not body.endswith("\n"):
            f.write("\n")

    print("wrote %s" % out_path)
    print("edit every REPLACE_ME before deploying it -- "
         "grep -n REPLACE_ME %s" % out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
